"""Implementer agent - writes code inside a sandbox."""

from __future__ import annotations

import re
from typing import List

from pqc_factory.agents.base import BaseAgent
from pqc_factory.agents.prompts import IMPLEMENTER_SYSTEM
from pqc_factory.models.agent_io import ImplementerResult


class ImplementerAgent(BaseAgent):
    def run(
        self,
        task: str,
        sandbox_id: str,
        context: str = "",
        feedback: str = "",
    ) -> ImplementerResult:
        user_content = f"Task:\n{task}\n\n"
        if context:
            user_content += f"Context / existing code:\n{context}\n\n"
        if feedback:
            user_content += f"Previous verifier feedback:\n{feedback}\n\n"
        user_content += "Please implement the required changes."

        messages = [
            {"role": "system", "content": IMPLEMENTER_SYSTEM},
            {"role": "user", "content": user_content},
        ]

        if self.llm.api_key.startswith("dummy"):
            return self._local_implement(task, sandbox_id)

        raw = self.llm.chat(messages, model=self.model)
        return self._parse(raw, sandbox_id)

    def _local_implement(self, task: str, sandbox_id: str) -> ImplementerResult:
        """Deterministic local implementation for tests / offline demos."""
        task_l = task.lower()
        changed: list[str] = []

        if "rate" in task_l and "limit" in task_l:
            rate_limiter = (
                '"""In-memory rate limiter - generated by PQC Implementer (local mode)."""\n\n'
                "from __future__ import annotations\n\n"
                "import time\n"
                "from collections import defaultdict, deque\n"
                "from dataclasses import dataclass\n"
                "from threading import Lock\n"
                "from typing import Deque, Dict\n\n\n"
                "@dataclass\n"
                "class RateLimitDecision:\n"
                "    allowed: bool\n"
                "    remaining: int\n"
                "    retry_after_seconds: float = 0.0\n\n\n"
                "class RateLimiter:\n"
                '    """Simple sliding-window rate limiter."""\n\n'
                "    def __init__(self, max_requests: int = 10, window_seconds: float = 60.0) -> None:\n"
                "        if max_requests < 1:\n"
                '            raise ValueError("max_requests must be >= 1")\n'
                "        if window_seconds <= 0:\n"
                '            raise ValueError("window_seconds must be > 0")\n'
                "        self.max_requests = max_requests\n"
                "        self.window_seconds = window_seconds\n"
                "        self._hits: Dict[str, Deque[float]] = defaultdict(deque)\n"
                "        self._lock = Lock()\n\n"
                '    def allow(self, key: str = "default") -> RateLimitDecision:\n'
                '        """Return whether a request for key is allowed right now."""\n'
                "        now = time.monotonic()\n"
                "        with self._lock:\n"
                "            q = self._hits[key]\n"
                "            cutoff = now - self.window_seconds\n"
                "            while q and q[0] < cutoff:\n"
                "                q.popleft()\n\n"
                "            if len(q) >= self.max_requests:\n"
                "                retry_after = self.window_seconds - (now - q[0]) if q else self.window_seconds\n"
                "                return RateLimitDecision(\n"
                "                    allowed=False,\n"
                "                    remaining=0,\n"
                "                    retry_after_seconds=max(0.0, retry_after),\n"
                "                )\n\n"
                "            q.append(now)\n"
                "            remaining = self.max_requests - len(q)\n"
                "            return RateLimitDecision(allowed=True, remaining=remaining)\n\n\n"
                "def solve() -> bool:\n"
                '    """Smoke-test helper used by the Verifier in local mode."""\n'
                "    rl = RateLimiter(max_requests=3, window_seconds=1.0)\n"
                '    assert rl.allow("user").allowed\n'
                '    assert rl.allow("user").allowed\n'
                '    assert rl.allow("user").allowed\n'
                '    denied = rl.allow("user")\n'
                "    assert not denied.allowed\n"
                "    return True\n"
            )
            test_code = (
                '"""Tests for RateLimiter."""\n\n'
                "from solution import RateLimiter, solve\n\n\n"
                "def test_allows_under_limit():\n"
                "    rl = RateLimiter(max_requests=5, window_seconds=60)\n"
                "    for _ in range(5):\n"
                '        assert rl.allow("a").allowed\n\n\n'
                "def test_denies_over_limit():\n"
                "    rl = RateLimiter(max_requests=2, window_seconds=60)\n"
                '    assert rl.allow("b").allowed\n'
                '    assert rl.allow("b").allowed\n'
                '    assert not rl.allow("b").allowed\n\n\n'
                "def test_remaining_decreases():\n"
                "    rl = RateLimiter(max_requests=3, window_seconds=60)\n"
                '    d1 = rl.allow("c")\n'
                "    assert d1.remaining == 2\n"
                '    d2 = rl.allow("c")\n'
                "    assert d2.remaining == 1\n\n\n"
                "def test_solve_smoke():\n"
                "    assert solve() is True\n"
            )
            self.sandbox.write_file(sandbox_id, "solution.py", rate_limiter)
            self.sandbox.write_file(sandbox_id, "test_solution.py", test_code)
            changed = ["solution.py", "test_solution.py"]
            thought = "Implemented a thread-safe sliding-window RateLimiter."
        else:
            filename = "solution.py"
            content = (
                '"""Auto-generated by PQC Implementer (local mode)."""\n\n'
                "def solve():\n"
                f'    """Implements: {task[:80]}"""\n'
                "    return True\n"
            )
            self.sandbox.write_file(sandbox_id, filename, content)
            changed = [filename]
            thought = "Local mode: created a minimal solution.py"

        return ImplementerResult(
            thought=thought,
            changed_files=changed,
            actions=[f"Wrote {f}" for f in changed],
            success=True,
            message="Local implementation complete",
        )

    def _parse(self, raw: str, sandbox_id: str) -> ImplementerResult:
        thought = ""
        changed: List[str] = []
        actions: List[str] = []

        thought_m = re.search(r"THOUGHT:\s*(.+?)(?=ACTIONS:|CHANGED_FILES:|$)", raw, re.S)
        if thought_m:
            thought = thought_m.group(1).strip()

        files_m = re.search(r"CHANGED_FILES:\s*(.+)", raw, re.S)
        if files_m:
            for line in files_m.group(1).splitlines():
                line = line.strip().lstrip("- ").strip()
                if line and not line.startswith("THOUGHT"):
                    changed.append(line)

        return ImplementerResult(
            thought=thought,
            changed_files=changed,
            actions=actions,
            success=True,
            message=raw[:500],
        )
