"""PR output package - turn a PQC report into a merge-ready artifact."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from pqc_factory.models.pqc_report import PQCReport
from pqc_factory.models.ticket import Ticket


@dataclass
class PRPackage:
    branch_name: str
    commit_message: str
    pr_title: str
    pr_body: str
    files_changed: List[str] = field(default_factory=list)
    risk_score: int = 50
    pr_ready: bool = False

    def to_dict(self) -> dict:
        return {
            "branch_name": self.branch_name,
            "commit_message": self.commit_message,
            "pr_title": self.pr_title,
            "pr_body": self.pr_body,
            "files_changed": self.files_changed,
            "risk_score": self.risk_score,
            "pr_ready": self.pr_ready,
        }

    def write(self, out_dir: str | Path = "./pqc_pr") -> Path:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "pr_body.md").write_text(self.pr_body, encoding="utf-8")
        (out / "pr_meta.json").write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")
        (out / "COMMIT_MSG.txt").write_text(self.commit_message, encoding="utf-8")
        return out


def build_pr_package(ticket: Ticket, report: PQCReport) -> PRPackage:
    slug = "".join(c if c.isalnum() else "-" for c in ticket.title.lower())[:40].strip("-")
    ts = datetime.now(timezone.utc).strftime("%Y%m%d")
    branch = f"pqc/{ts}-{slug}"
    commit = f"pqc: {ticket.title}\n\nScore={report.overall_score:.1f} risk={report.risk_score} status={report.status.value}"
    title = f"[PQC] {ticket.title}"
    body = report.to_markdown() + "\n\n---\n_Generated by Production-Qualified Change Factory_\n"
    return PRPackage(
        branch_name=branch,
        commit_message=commit,
        pr_title=title,
        pr_body=body,
        files_changed=list(report.changed_files),
        risk_score=report.risk_score,
        pr_ready=report.pr_ready,
    )


def create_github_draft_pr(
    package: PRPackage,
    owner: str,
    repo: str,
    base: str = "main",
    token: Optional[str] = None,
) -> Optional[dict]:
    import os
    import httpx

    token = token or os.getenv("GITHUB_TOKEN")
    if not token:
        return None
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    payload = {
        "title": package.pr_title,
        "head": package.branch_name,
        "base": base,
        "body": package.pr_body,
        "draft": True,
    }
    try:
        r = httpx.post(url, headers=headers, json=payload, timeout=30)
        if r.status_code in (200, 201):
            return r.json()
        return {"error": r.status_code, "body": r.text[:500]}
    except Exception as e:
        return {"error": str(e)}
